version: "2"
services:
  mq:
    image: "rabbitmq:3.6.10-management-alpine"
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    expose:
      - 5672
      - 15671
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "admin"